[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error = "0.1.9"
ordered-float = "4.2.2"
serde = { version = "1.0.207", features = ["derive"] }
serde_json = "1.0.124"
skiplist = "0.5.1"
